#include <hal.h>

void boardInit(void) {

    palSetLineMode(BOARD_PAL_LINE_CAN_RX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN_TX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);

    palSetLineMode(BOARD_PAL_LINE_I2C2_SDA, PAL_MODE_ALTERNATE(4) |  PAL_STM32_OTYPE_OPENDRAIN | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_I2C2_SCL, PAL_MODE_ALTERNATE(4) |  PAL_STM32_OTYPE_OPENDRAIN | PAL_STM32_OSPEED_HIGHEST);

    palSetLineMode(BOARD_PAL_LINE_LED, PAL_MODE_ALTERNATE(0) | PAL_STM32_MODE_OUTPUT);
}
