#include <hal.h>

void boardInit(void) {

    palSetLineMode(BOARD_PAL_LINE_CAN_RX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN_TX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);

    palSetLineMode(BOARD_PAL_LINE_I2C2_SDA, PAL_MODE_ALTERNATE(4));
    palSetLineMode(BOARD_PAL_LINE_I2C2_SCL, PAL_MODE_ALTERNATE(4));

    palSetPadMode(GPIOA, 0 , PAL_MODE_OUTPUT_PUSHPULL);
    palSetPadMode(GPIOA, 1 , PAL_MODE_OUTPUT_PUSHPULL);
}
